# Chapter 1 Vectors, Matrices, and Arrays

## Creating a Vector and a Matrix

In [2]:
# Load library
import numpy as np
# Create a vector as a row
vector_row = np.array([1, 2, 3])
# Create a vector as a column
vector_column = np.array([[1],
                        [2],
                        [3]])
print(vector_row)
print(vector_column)

matrix = np.array([[1, 2],
                [1, 2],
                [1, 2]])
print(matrix)

[1 2 3]
[[1]
 [2]
 [3]]


## Creating a Sparse Matrix

`sparse.csr_matrix(matrix)` returns the position of nonzero element and the value of element in a line.

稀疏矩阵只存储非零元素，并假设所有其他的值都是零，这将大大节省计算量。

In [5]:
# Load libraries
import numpy as np
from scipy import sparse
# Create a matrix
matrix = np.array([[0, 0],
[0, 1],
[3, 0]])
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix)
print(matrix_sparse)

[[0 0]
 [0 1]
 [3 0]]
  (1, 1)	1
  (2, 0)	3


## Selecting Elements

In [9]:
# Load library
import numpy as np
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Select third element of vector
vector[2]
# Select second row, second column
matrix[1,1]

3

## Describing a Matrix

In [11]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])
# View number of rows and columns
matrix.shape
(3, 4)
# View number of elements (rows * columns)
matrix.size
12
# View number of dimensions
matrix.ndim
2

2

## Applying Operations to Elements

这里用了lambda匿名函数，但是设置匿名函数输入针对单元素`i`，然后使用`vectorize`函数将其转换为面向矩阵的函数。

NumPy的vectorize类将一个函数转换为一个可以应用于数组或数组切片中所有元素的函数。值得注意的是，vectorize本质上是对元素的for循环，并不能提高性能。

In [13]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Create function that adds 100 to something
add_100 = lambda i: i + 100
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## Finding the Maximum and Minimum Values

In [14]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
# Return maximum element
np.max(matrix)
9
# Return minimum element
np.min(matrix)
1

1

In [16]:
# Find maximum element in each column
np.max(matrix, axis=0)
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

## Calculating the Average, Variance, and Standard Deviation

In [17]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
np.mean(matrix)
5.0
# Return variance
np.var(matrix)
6.666666666666667
# Return standard deviation
np.std(matrix)
2.5819888974716112

2.581988897471611

## Reshaping and Flattening a Matrix

In [32]:
# Load library
import numpy as np
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)
# 用一种更通用的手段
matrix.reshape(2, matrix.size//2)
# 但其实可以更方便，使用-1
matrix.reshape(2, -1)
# array([[ 1, 2, 3, 4, 5, 6],
# [ 7, 8, 9, 10, 11, 12]])


# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Flatten matrix
matrix.flatten()
# array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
                [7, 8, 9],
                [10, 11, 12]])
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)
# 用一种更通用的手段
matrix.reshape(2, matrix.size//2)
# 但其实可以更方便，使用-1
matrix.reshape(2, -1)
# array([[ 1, 2, 3, 4, 5, 6],
# [ 7, 8, 9, 10, 11, 12]])


# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Flatten matrix
matrix.flatten()
# array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
matrix = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)
# 用一种更通用的手段
matrix.reshape(2, matrix.size//2)
# 但其实可以更方便，使用-1
matrix.reshape(2, -1)
# array([[ 1, 2, 3, 4, 5, 6],
# [ 7, 8, 9, 10, 11, 12]])


# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Flatten matrix
matrix.flatten()
# array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Transposing a Vector or Matrix

In [33]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Transpose matrix
matrix.T
# array([[1, 4, 7],
# [2, 5, 8],
# [3, 6, 9]])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## The Rank, Determinant, Diagonal of a Matrix

In [39]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 1, 1],
                    [1, 1, 10],
                    [1, 1, 15]])
# Return matrix rank
np.linalg.matrix_rank(matrix)
np.linalg.det(matrix)
# Return diagonal elements
matrix.diagonal()
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)
# Return trace
matrix.trace()

17

## Finding Eigenvalues and Eigenvectors

In [41]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, -1, 3],
                    [1, 1, 6],
                    [3, 8, 9]])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
# View eigenvalues
print(eigenvalues)
# array([ 13.55075847, 0.74003145, -3.29078992])
# View eigenvectors
print(eigenvectors)
# array([[-0.17622017, -0.96677403, -0.53373322],
# [-0.435951 , 0.2053623 , -0.64324848],
# [-0.88254925, 0.15223105, 0.54896288]])

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


## Dot Products of Vector - Adding, Subtracting and Multiplying, Inverting  Matrices

In [56]:
# Load library
import numpy as np
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
# Calculate dot product
np.dot(vector_a, vector_b)
# in Python 3.5+ we can use the new @ operator:
vector_a @ vector_b

# Create matrix
matrix_a = np.array([[1, 1, 1],
                    [1, 1, 1],
                    [1, 1, 2]])
# Create matrix
matrix_b = np.array([[1, 3, 1],
                    [1, 3, 1],
                    [1, 3, 8]])
# Add two matrices
np.add(matrix_a, matrix_b)
# array([[ 2, 4, 2],
# [ 2, 4, 2],
# [ 2, 4, 10]])
# Subtract two matrices
np.subtract(matrix_a, matrix_b)
# array([[ 0, -2, 0],
# [ 0, -2, 0],
# [ 0, -2, -6]])

# Alternatively, we can simply use the + and - operators:
matrix_a + matrix_b

# Multiply two matrices
np.dot(matrix_a, matrix_b)
# dot multiply two matrices
matrix_a @ matrix_b
# Multiply two matrices element-wise
matrix_a * matrix_b


# Create matrix
matrix = np.array([[1, 4],
[2, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)
# array([[-1.66666667, 1.33333333],
# [ 0.66666667, -0.33333333]])


array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

## Generating Random Values

随机种子（Random Seed）是计算机专业术语，一种以随机数作为对象的以真随机数（种子）为初始条件的随机数。一般计算机的随机数都是伪随机数，以一个真随机数（种子）作为初始条件，然后用一定的算法不停迭代产生随机数

In [75]:
# Load library
import numpy as np
# Set seed
np.random.seed(0)
# Generate three random floats between 0.0 and 1.0
np.random.random(3)
# array([ 0.5488135 , 0.71518937, 0.60276338])
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)
# array([3, 7, 9])

# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)
# array([-1.42232584, 1.52006949, -0.29139398])
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)
# array([-0.98118713, -0.08939902, 1.46416405])
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)
# array([ 1.47997717, 1.3927848 , 1.83607876])

array([3, 7, 9])